### ISSUE TITLE
contact informations from darwin calendarserver lost

### ISSUE THREAD

**Issue by lexusburn** [christian-putzke/CardDAV-PHP#6]
hello,

now i get get the contacts from my darwin calendarserver.
but i miss some informations like private and business address, some mail-adresses, some phone numbers, relations to other persons and URLs.

you can get an example of an vcard with all of these informations here: http://dl.dropbox.com/u/177312/D43BE77F-AA32-4F69-8923-B1CF73365AE7-ABSPlugin.vcf

**Comment by christian-putzke** [comment]
Hi!
That seems not to be a problem of my CardDAV Client. If you compare the vCard from your darwin calendar server with the vCard that my Roundcube CardDAV Plugin writes into the database (carddav_contacts) then these vCards should be exactly the same. The problem is that the Roundcube addressbook itself can't handle all data from your vCards. It's seems that the darwin calendar server does not produce standard conform vCard parameters so that Roundcube can't read them correctly. But that is something that the darwin calendar server developers and/or the Roundcube developers hvae to fix.
